Repository google/temporian, pull requests merged in 2023-03, with the labels that each got.

#25 improve readme
  README.md
  resources/banner.png
Labels: documentation

#23 DataFrame <-> NumpyEvent
  temporian/core/data/duration.py
  temporian/implementation/numpy/data/BUILD
  temporian/implementation/numpy/data/event.py
  temporian/implementation/numpy/data/tests/BUILD
  temporian/implementation/numpy/data/tests/test_df_to_event.py
  temporian/implementation/numpy/data/tests/test_event_to_df.py
Labels: enhancement

#30 Update Readme: Add reference to the credits
  README.md
Labels: documentation

#28 Select tests
  temporian/implementation/numpy/operators/tests/BUILD
  temporian/implementation/numpy/operators/tests/select_test.py
  temporian/test/prototype_test_numpy.py
Labels: enhancement

#27 Remove pandas backend
  temporian/core/BUILD
  temporian/core/backends.py
  temporian/core/evaluator.py
  temporian/implementation/numpy/data/tests/BUILD
  temporian/implementation/numpy/operators/BUILD
  temporian/implementation/pandas/BUILD
  temporian/implementation/pandas/__init__.py
  temporian/implementation/pandas/data/BUILD
  temporian/implementation/pandas/data/__init__.py
  temporian/implementation/pandas/data/event.py
  temporian/implementation/pandas/data/sampling.py
  temporian/implementation/pandas/data/tests/BUILD
  temporian/implementation/pandas/data/tests/test_sampling.py
  temporian/implementation/pandas/evaluator.py
  temporian/implementation/pandas/operators/BUILD
  temporian/implementation/pandas/operators/__init__.py
  temporian/implementation/pandas/operators/assign.py
  temporian/implementation/pandas/operators/base.py
  temporian/implementation/pandas/operators/core_mapping.py
  temporian/implementation/pandas/operators/select.py
  temporian/implementation/pandas/operators/tests/__init__.py
  temporian/implementation/pandas/operators/tests/assign/BUILD
  temporian/implementation/pandas/operators/tests/assign/__init__.py
  temporian/implementation/pandas/operators/tests/assign/assign_test.py
  temporian/implementation/pandas/operators/tests/assign/test_data/BUILD
  temporian/implementation/pandas/operators/tests/assign/test_data/__init__.py
  temporian/implementation/pandas/operators/tests/assign/test_data/different_index.py
  temporian/implementation/pandas/operators/tests/assign/test_data/repeated_timestamps.py
  temporian/implementation/pandas/operators/tests/assign/test_data/with_idx_more_timestamps.py
  temporian/implementation/pandas/operators/tests/assign/test_data/with_idx_same_timestamps.py
  temporian/implementation/pandas/operators/window/BUILD
  temporian/implementation/pandas/operators/window/__init__.py
  temporian/implementation/pandas/operators/window/base.py
  temporian/implementation/pandas/operators/window/simple_moving_average.py
  temporian/implementation/pandas/operators/window/tests/__init__.py
  temporian/implementation/pandas/operators/window/tests/simple_moving_average/BUILD
  temporian/implementation/pandas/operators/window/tests/simple_moving_average/__init__.py
  temporian/implementation/pandas/operators/window/tests/simple_moving_average/data/BUILD
  temporian/implementation/pandas/operators/window/tests/simple_moving_average/data/__init__.py
  temporian/implementation/pandas/operators/window/tests/simple_moving_average/data/diff_sampling.py
  temporian/implementation/pandas/operators/window/tests/simple_moving_average/data/many_events_per_day.py
  temporian/implementation/pandas/operators/window/tests/simple_moving_average/data/many_features.py
  temporian/implementation/pandas/operators/window/tests/simple_moving_average/data/no_index.py
  temporian/implementation/pandas/operators/window/tests/simple_moving_average/data/same_sampling.py
  temporian/implementation/pandas/operators/window/tests/simple_moving_average/test.py
  temporian/implementation/pandas/utils.py
  temporian/test/api_test.py
Labels: enhancement

#31 Calendar operators
  temporian/BUILD
  temporian/__init__.py
  temporian/core/operators/BUILD
  temporian/core/operators/__init__.py
  temporian/core/operators/calendar_day_of_month.py
  temporian/implementation/numpy/data/event.py
  temporian/implementation/numpy/operators/BUILD
  temporian/implementation/numpy/operators/arithmetic.py
  temporian/implementation/numpy/operators/calendar_day_of_month.py
  temporian/implementation/numpy/operators/lag.py
  temporian/implementation/numpy/operators/tests/BUILD
  temporian/implementation/numpy/operators/tests/arithmetic_test.py
  temporian/implementation/numpy/operators/tests/assign_test.py
  temporian/implementation/numpy/operators/tests/calendar_day_of_month_test.py
  temporian/implementation/numpy/operators/tests/lag_test.py
  temporian/test/prototype_test_numpy.py
Labels: enhancement, needs cross review

#29 Read & Save Event
  temporian/BUILD
  temporian/__init__.py
  temporian/io/BUILD
  temporian/io/__init__.py
  temporian/io/read_event.py
  temporian/io/save_event.py
  temporian/test/BUILD
  temporian/test/io_test.py
  temporian/test/test_data/io/input.csv
Labels: enhancement

#26 Finish Numpy SMA backend
  temporian/core/backends.py
  temporian/core/data/duration.py
  temporian/core/evaluator.py
  temporian/core/operators/base.py
  temporian/core/operators/simple_moving_average.py
  temporian/core/test/evaluator_test.py
  temporian/implementation/numpy/evaluator.py
  temporian/implementation/numpy/operators/BUILD
  temporian/implementation/numpy/operators/assign.py
  temporian/implementation/numpy/operators/core_mapping.py
  temporian/implementation/numpy/operators/simple_moving_average.py
  temporian/implementation/numpy/operators/tests/BUILD
  temporian/implementation/numpy/operators/tests/simple_moving_average_test.py
  temporian/implementation/numpy/operators/window/BUILD
  temporian/implementation/numpy/operators/window/__init__.py
  temporian/implementation/numpy/operators/window/base.py
  temporian/implementation/numpy/operators/window/simple_moving_average.py
  temporian/implementation/numpy/operators/window/test/BUILD
  temporian/implementation/numpy/operators/window/test/__init__.py
  temporian/implementation/numpy/operators/window/test/simple_moving_average_test.py
  temporian/test/api_test.py
  temporian/test/prototype_test_numpy.py
Labels: enhancement, needs cross review

#39 Fix NumpyEvent schema
  temporian/core/operators/arithmetic.py
  temporian/implementation/numpy/data/event.py
  temporian/test/prototype_test_numpy.py
Labels: bug

#54 move calendar operators to subdir in core and numpy
  temporian/BUILD
  temporian/__init__.py
  temporian/core/operators/BUILD
  temporian/core/operators/calendar/BUILD
  temporian/core/operators/calendar/__init__.py
  temporian/core/operators/calendar/base.py
  temporian/core/operators/calendar/day_of_month.py
  temporian/core/operators/calendar/day_of_week.py
  temporian/implementation/numpy/operators/BUILD
  temporian/implementation/numpy/operators/calendar/BUILD
  temporian/implementation/numpy/operators/calendar/__init__.py
  temporian/implementation/numpy/operators/calendar/base.py
  temporian/implementation/numpy/operators/calendar/day_of_month.py
  temporian/implementation/numpy/operators/calendar/day_of_week.py
  temporian/implementation/numpy/operators/calendar_day_of_month.py
  temporian/implementation/numpy/operators/tests/BUILD
  temporian/implementation/numpy/operators/tests/calendar_day_of_month_test.py
  temporian/implementation/numpy/operators/tests/calendar_day_of_week_test.py
Labels: enhancement

#53 Unix timestamp samplings
  temporian/core/data/duration.py
  temporian/core/data/sampling.py
  temporian/core/operators/calendar/base.py
  temporian/implementation/numpy/data/event.py
  temporian/implementation/numpy/data/sampling.py
  temporian/implementation/numpy/data/tests/test_df_to_event.py
  temporian/implementation/numpy/operators/tests/calendar_day_of_month_test.py
Labels: enhancement

#50 Support String in `NumpyEvent.from_dataframe()`
  temporian/implementation/numpy/data/event.py
  temporian/implementation/numpy/data/tests/test_df_to_event.py
Labels: bug

#41 Propagate operator
  temporian/core/data/event.py
  temporian/core/operators/BUILD
  temporian/core/operators/propagate.py
  temporian/core/operators/select.py
  temporian/core/operators/test/BUILD
  temporian/core/operators/test/propagate_test.py
  temporian/core/test/BUILD
  temporian/core/test/evaluator_test.py
  temporian/core/test/utils.py
  temporian/implementation/numpy/data/BUILD
  temporian/implementation/numpy/data/event.py
  temporian/implementation/numpy/data/sampling.py
  temporian/implementation/numpy/data/tests/BUILD
  temporian/implementation/numpy/data/tests/event_test.py
  temporian/implementation/numpy/operators/BUILD
  temporian/implementation/numpy/operators/core_mapping.py
  temporian/implementation/numpy/operators/propagate.py
  temporian/implementation/numpy/operators/tests/BUILD
  temporian/implementation/numpy/operators/tests/propagate_test.py
  temporian/utils/BUILD
  temporian/utils/string.py
  temporian/utils/test/BUILD
  temporian/utils/test/string_test.py
Labels: needs cross review

#43 Create register mechanism for op implementation + runtime check of of op definition vs op results
  temporian/BUILD
  temporian/__init__.py
  temporian/core/BUILD
  temporian/core/backends.py
  temporian/core/core.py
  temporian/core/data/feature.py
  temporian/core/data/sampling.py
  temporian/core/evaluator.py
  temporian/core/operator_lib.py
  temporian/core/operators/BUILD
  temporian/core/operators/all_operators.py
  temporian/core/operators/arithmetic.py
  temporian/core/operators/assign.py
  temporian/core/operators/base.py
  temporian/core/operators/lag.py
  temporian/core/operators/propagate.py
  temporian/core/operators/select.py
  temporian/core/operators/simple_moving_average.py
  temporian/core/serialize.py
  temporian/core/test/BUILD
  temporian/core/test/processor_test.py
  temporian/core/test/registered_operators_test.py
  temporian/implementation/numpy/BUILD
  temporian/implementation/numpy/data/event.py
  temporian/implementation/numpy/evaluator.py
  temporian/implementation/numpy/implementation_lib.py
  temporian/implementation/numpy/operators/BUILD
  temporian/implementation/numpy/operators/all_operators.py
  temporian/implementation/numpy/operators/arithmetic.py
  temporian/implementation/numpy/operators/assign.py
  temporian/implementation/numpy/operators/calendar/BUILD
  temporian/implementation/numpy/operators/calendar/day_of_month.py
  temporian/implementation/numpy/operators/calendar/day_of_week.py
  temporian/implementation/numpy/operators/core_mapping.py
  temporian/implementation/numpy/operators/lag.py
  temporian/implementation/numpy/operators/propagate.py
  temporian/implementation/numpy/operators/select.py
  temporian/implementation/numpy/operators/simple_moving_average.py
  temporian/implementation/numpy/operators/test/select_test.py
  temporian/implementation/numpy/operators/test/simple_moving_average_test.py
  temporian/implementation/numpy/test/BUILD
  temporian/implementation/numpy/test/registered_operators_test.py
  temporian/test/BUILD
  temporian/test/api_test.py
  temporian/test/prototype_test_numpy.py
Labels: needs cross review

#55 Support Duration List in Lag
  temporian/core/operators/lag.py
  temporian/implementation/numpy/operators/test/BUILD
  temporian/implementation/numpy/operators/test/lag_test.py
Labels: enhancement, needs cross review

#61 Check np.object column is only of type str
  temporian/implementation/numpy/data/event.py
  temporian/implementation/numpy/data/test/df_to_event_test.py
Labels: bug

#63 Migrate from `np.string_` to `np.str_`
  temporian/implementation/numpy/data/event.py
  temporian/implementation/numpy/data/test/df_to_event_test.py
  temporian/implementation/numpy/data/test/event_to_df_test.py
Labels: bug
