Repository google/temporian, pull requests merged in 2023-04, with the labels that each got.

#51 DropIndexOperator
  temporian/core/data/event.py
  temporian/core/data/sampling.py
  temporian/core/operators/BUILD
  temporian/core/operators/drop_index.py
  temporian/implementation/numpy/data/event.py
  temporian/implementation/numpy/data/feature.py
  temporian/implementation/numpy/data/sampling.py
  temporian/implementation/numpy/operators/BUILD
  temporian/implementation/numpy/operators/drop_index.py
  temporian/implementation/numpy/operators/test/BUILD
  temporian/implementation/numpy/operators/test/drop_index_test.py
  temporian/proto/core.proto
Labels: enhancement

#73 Sort DataFrame by Timestamps
  temporian/implementation/numpy/data/event.py
  temporian/implementation/numpy/data/test/df_to_event_test.py
Labels: bug, needs cross review

#81 Split arithmetic operators into subclasses
  temporian/core/data/event.py
  temporian/core/operators/BUILD
  temporian/core/operators/all_operators.py
  temporian/core/operators/arithmetic.py
  temporian/core/operators/arithmetic/BUILD
  temporian/core/operators/arithmetic/__init__.py
  temporian/core/operators/arithmetic/add.py
  temporian/core/operators/arithmetic/base.py
  temporian/core/operators/arithmetic/divide.py
  temporian/core/operators/arithmetic/floordiv.py
  temporian/core/operators/arithmetic/multiply.py
  temporian/core/operators/arithmetic/subtract.py
  temporian/core/operators/test/BUILD
  temporian/core/operators/test/arithmetic_test.py
  temporian/core/test/registered_operators_test.py
  temporian/implementation/numpy/operators/BUILD
  temporian/implementation/numpy/operators/all_operators.py
  temporian/implementation/numpy/operators/arithmetic/BUILD
  temporian/implementation/numpy/operators/arithmetic/__init__.py
  temporian/implementation/numpy/operators/arithmetic/add.py
  temporian/implementation/numpy/operators/arithmetic/base.py
  temporian/implementation/numpy/operators/arithmetic/divide.py
  temporian/implementation/numpy/operators/arithmetic/floordiv.py
  temporian/implementation/numpy/operators/arithmetic/multiply.py
  temporian/implementation/numpy/operators/arithmetic/subtract.py
  temporian/implementation/numpy/operators/test/BUILD
  temporian/implementation/numpy/operators/test/arithmetic_multi_index_test.py
  temporian/implementation/numpy/operators/test/arithmetic_test.py
  temporian/implementation/numpy/test/registered_operators_test.py
Labels: enhancement, needs cross review

#89 Filter Operator
  temporian/core/data/dtype.py
  temporian/core/data/sampling.py
  temporian/core/operators/BUILD
  temporian/core/operators/all_operators.py
  temporian/core/operators/filter.py
  temporian/core/test/registered_operators_test.py
  temporian/implementation/numpy/data/event.py
  temporian/implementation/numpy/data/feature.py
  temporian/implementation/numpy/operators/BUILD
  temporian/implementation/numpy/operators/all_operators.py
  temporian/implementation/numpy/operators/filter.py
  temporian/implementation/numpy/operators/test/BUILD
  temporian/implementation/numpy/operators/test/filter_test.py
  temporian/implementation/numpy/test/registered_operators_test.py
Labels: enhancement, needs cross review

#99 Example of notebook
  .gitignore
  example/.ipynb_checkpoints/Playing with notebook-checkpoint.ipynb
  example/toy_example.ipynb
  example/vital_signs.ipynb
  pyproject.toml
  tools/start_notebook.sh
Labels: documentation

#100 Remove Lag Operator auto naming
  temporian/core/operators/lag.py
  temporian/implementation/numpy/operators/lag.py
  temporian/implementation/numpy/operators/test/lag_test.py
  temporian/test/prototype_test_numpy.py
Labels: enhancement

#91 Cast operator
  benchmark/benchmark_time.py
  temporian/__init__.py
  temporian/core/operators/BUILD
  temporian/core/operators/all_operators.py
  temporian/core/operators/arithmetic.py
  temporian/core/operators/cast.py
  temporian/core/test/registered_operators_test.py
  temporian/implementation/numpy/operators/BUILD
  temporian/implementation/numpy/operators/all_operators.py
  temporian/implementation/numpy/operators/cast.py
  temporian/implementation/numpy/operators/drop_index.py
  temporian/implementation/numpy/operators/set_index.py
  temporian/implementation/numpy/operators/test/BUILD
  temporian/implementation/numpy/operators/test/cast_test.py
  temporian/implementation/numpy/test/registered_operators_test.py
  temporian/proto/core.proto
Labels: enhancement, needs cross review

#82 Docstrings
  CONTRIBUTING.md
  benchmark/scripts/basic.py
  benchmark/scripts/sma.py
  docs/docstring_guidelines.md
  temporian/core/data/dtype.py
  temporian/core/data/duration.py
  temporian/core/data/event.py
  temporian/core/data/feature.py
  temporian/core/data/sampling.py
  temporian/core/evaluator.py
  temporian/core/operator_lib.py
  temporian/core/operators/arithmetic.py
  temporian/core/operators/base.py
  temporian/core/operators/calendar/base.py
  temporian/core/operators/calendar/day_of_month.py
  temporian/core/operators/calendar/day_of_week.py
  temporian/core/operators/calendar/day_of_year.py
  temporian/core/operators/calendar/hour.py
  temporian/core/operators/calendar/iso_week.py
  temporian/core/operators/calendar/minute.py
  temporian/core/operators/calendar/month.py
  temporian/core/operators/calendar/second.py
  temporian/core/operators/calendar/year.py
  temporian/core/operators/glue.py
  temporian/core/operators/lag.py
  temporian/core/operators/prefix.py
  temporian/core/operators/propagate.py
  temporian/core/operators/sample.py
  temporian/core/operators/select.py
  temporian/core/operators/window/base.py
  temporian/core/operators/window/moving_count.py
  temporian/core/operators/window/moving_standard_deviation.py
  temporian/core/operators/window/moving_sum.py
  temporian/core/operators/window/simple_moving_average.py
  temporian/core/processor.py
  temporian/core/serialize.py
  temporian/core/test/serialize_test.py
  temporian/implementation/numpy/data/event.py
  temporian/implementation/numpy/data/plotter.py
  temporian/implementation/numpy/data/sampling.py
  temporian/implementation/numpy/evaluator.py
  temporian/implementation/numpy/implementation_lib.py
  temporian/implementation/numpy/operators/arithmetic.py
  temporian/implementation/numpy/operators/base.py
  temporian/implementation/numpy/operators/calendar/base.py
  temporian/implementation/numpy/operators/glue.py
  temporian/implementation/numpy/operators/lag.py
  temporian/implementation/numpy/operators/prefix.py
  temporian/implementation/numpy/operators/propagate.py
  temporian/implementation/numpy/operators/sample.py
  temporian/implementation/numpy/operators/select.py
  temporian/implementation/numpy/operators/window/base.py
  temporian/implementation/numpy/operators/window/moving_count.py
  temporian/implementation/numpy/operators/window/moving_standard_deviation.py
  temporian/implementation/numpy/operators/window/moving_sum.py
  temporian/implementation/numpy/operators/window/simple_moving_average.py
  temporian/io/read_event.py
  temporian/io/save_event.py
  temporian/utils/string.py
Labels: documentation

#96 Optimize `from_df()`
  benchmark/benchmark_time.py
  temporian/implementation/numpy/data/event.py
  temporian/implementation/numpy/data/sampling.py
  temporian/implementation/numpy/data/test/df_to_event_test.py
Labels: optimization

#109 Rename operator
  README.md
  temporian/core/data/event.py
  temporian/core/operators/BUILD
  temporian/core/operators/all_operators.py
  temporian/core/operators/rename.py
  temporian/core/test/registered_operators_test.py
  temporian/implementation/numpy/operators/BUILD
  temporian/implementation/numpy/operators/all_operators.py
  temporian/implementation/numpy/operators/base.py
  temporian/implementation/numpy/operators/rename.py
  temporian/implementation/numpy/operators/test/BUILD
  temporian/implementation/numpy/operators/test/rename_test.py
  temporian/implementation/numpy/test/registered_operators_test.py
Labels: enhancement
